### PR TITLE
[TCHL-69] First GUI implementation with Streamlit

### PR DESCRIPTION
**Pull request by FabioMeneghini**
Install Streamlit with the command `pip install streamlit`, then `streamlit run guiUser.py` to run the graphical application.
Every python file used by the graphical application has a name that starts with "gui".

> [!IMPORTANT]
You also need to install the `keyboard` and `psutil` modules with pip

### CODE REVIEW

**Review by giovannifil-64 — CHANGES_REQUESTED** [review]
The file will not be uploaded if it does not comply with the schema, and this works flawlessly.
If an attempt is made to upload a compliant file, the following error will be displayed:

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Marco\\Desktop\\swe\\progetto\\ChatSQL\\ChatSQL\\code\\..\\database\\corso_universitario.json'
Traceback:
File "C:\Users\Marco\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 530, in _run_script
    self._session_state.on_script_will_rerun(rerun_data.widget_states)
File "C:\Users\Marco\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 61, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
File "C:\Users\Marco\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\state\session_state.py", line 500, in on_script_will_rerun
    self._call_callbacks()
File "C:\Users\Marco\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\state\session_state.py", line 513, in _call_callbacks
    self._new_widget_state.call_callback(wid)
File "C:\Users\Marco\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\state\session_state.py", line 260, in call_callback
    callback(*args, **kwargs)
File "C:\Users\Marco\Desktop\swe\progetto\ChatSQL\ChatSQL\code\pages\guiAdmin.py", line 16, in upload
    message=uploadFile(st.session_state.uploaded_file.read(), st.session_state.uploaded_file.name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Marco\Desktop\swe\progetto\ChatSQL\ChatSQL\code\guiFileOperations.py", line 64, in uploadFile
    with open(destination_path, "wb") as destination_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The issue appears to be with the generated path.

**Comment by giovannifil-64** [comment]
@FabioMeneghini @MarcoCappellari The previously reported error has been fixed in [175bad5](https://github.com/Torchlight-SWE2324/ChatSQL/pull/12/commits/175bad5397a462fec836f75b7852c13c4e4d0a77).

**Review by MarcoCappellari — APPROVED** [review]
Con le modifche di @giovannifil-64 funziona

**Review by giovannifil-64 — APPROVED** [review]
Works flawlessly. LGTM

**Review by Dmitry358 — APPROVED** [review]
Ok

**Review by AriannaDela — APPROVED** [review]

**Review by FedeYe — COMMENTED** [review]
The interface works fine.  Here are some errors that i have discovered while doing the testing and not banal improvements that can be done:

- Problems:
1. There is a error when i try to delete the file of the database that is currently selected -> how to deal with it?
2. The embedding system doesn't work at all -> when asked "list of movies", the prompt has a 0.25 score and it contains all the tables from the datase with all their columns intead of only the MOVIES table;
3. when asked a not inherent question , the prompt is still returned with some tables when it shouldn't;
4. Debuggin should be more clear with the score of the top x number of columns.

- Enhancement :
1. make the delete section stand out more from the rest of the UI because of it's importance (too similar to the selet database section);
2. once uploaded successfully, the uploaded file should be removed form the upload section;
3. the applications switches automatically to the new database, should it happen? maybe a message that asks the admin if he wants to switch;

**Pull request merged**
